Generic Whitelist
public-awesome/names pull request #145
Opened 2022-11-01 19:32 UTC by humanalgorithm

Copying the code for whitelist-updatable but making it for Str's instead of Addr's.

Reason for doing this is so that we can use a whitelist for non-cosmo addresses such as Ethereum.  

Reason for not using a configurable contract is that DRY principles do not apply the same in contract programming as in object-oriented programming
Better to have two different contracts that can be selected by the invoking contract at will

2022-11-01 20:42 UTC, yubrew commented
since this is not names related, might want to stick it in a different repo, launchpad seems to make more sense

2022-11-02 02:08 UTC, shanev requested changes
Let's move this to the Launchpad repo as that's where it's most useful. This repo is specifically for Names.

2022-11-03 03:48 UTC, humanalgorithm commented
> Let's move this to the Launchpad repo as that's where it's most useful. This repo is specifically for Names.

Per the intractable problem of the cyclical dependencies, we are going to leave this package in this repo for now

2022-11-03 14:30 UTC, shanev approved these changes

2022-11-03 14:30 UTC, merged